# ################################
# Model: patchies + DNN + CTC
# Augmentation: SpecAugment
# Authors: Sung-Lin Yeh 2021
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1993
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/train_patchies_char/<seed>
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Data files
data_folder: /datasets/TALN/speech/eng/librispeech/audio/LibriSpeech # e,g./path/to/LibriSpeech
# noise/ris dataset will automatically be downloaded
data_folder_rirs: !ref <data_folder>
train_splits: ["train-clean-100", "train-clean-360", "train-other-500"]
dev_splits: ["dev-clean"]
test_splits: ["test-clean", "test-other"]
skip_prep: False
ckpt_interval_minutes: 25 # save checkpoint every N min
train_csv: !ref <output_folder>/train.csv
valid_csv: !ref <output_folder>/dev-clean.csv
test_csv:
   - !ref <output_folder>/test-clean.csv
   - !ref <output_folder>/test-other.csv

# Training parameters
number_of_epochs: 1
lr: 0.9
lr_patchies: 0.0001
sorting: ascending
batch_ordering: !ref <sorting>
auto_mix_prec: False
sample_rate: 16000

# Model featurizer parameters
n_mels: 80
hop_length: 10

# Patcher parameters
max_global_shift: 0.0
max_local_shift: 0.0
max_global_scaling: 1.0
normalize_pos_emb: False

# Model training patch specific parameters
patch_sizes: [[1, 80]]
patch_strides: [[1, 80]]
target_patch_size: [1, 80]
feat_patch_projector_patch_size: [[1, 80]] # [!ref <target_patch_size>]
target_patch_stride: [1, 80]
d_model: 768
apply_mask: True
loss_masked_only: True
mask_length: 2
mask_prob: 0.065
mask_dim: 512
upsampling_factor: 1 # patch_size_t / target_patch_size_t
feat_projector_dropout: 0.1
decoder_pos_emb_freq_scale: 10 # hop_length * patch_size_t
feat_patch_projector_dropout: 0.0


# With data_parallel batch_size is split into N jobs
# With DDP batch_size is multiplied by N jobs
# Must be 3 per GPU to fit 32GB of VRAM
batch_size: 6
test_batch_size: 8

# Dataloader options
train_dataloader_opts:
   batch_size: !ref <batch_size>

valid_dataloader_opts:
   batch_size: !ref <batch_size>

test_dataloader_opts:
   batch_size: !ref <test_batch_size>

# Model parameters
activation: !name:torch.nn.LeakyReLU
dnn_layers: 2
dnn_neurons: 1024
freeze_patchies: True

# Outputs
output_neurons: 31  # BPE size, index(blank/eos/bos) = 0

# Decoding parameters
blank_index: 0
bos_index: 1
eos_index: 2

#
# Functions and classes
#
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
   limit: !ref <number_of_epochs>

augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
   sample_rate: !ref <sample_rate>
   speeds: [95, 100, 105]

enc: !new:speechbrain.lobes.models.VanillaNN.VanillaNN
   input_shape: [null, null, 768]
   activation: !ref <activation>
   dnn_blocks: !ref <dnn_layers>
   dnn_neurons: !ref <dnn_neurons>

pretrained: '/homedtic/gcambara/projects/2022/multipatch-ssl/git/sb_dev/recipes/LibriSpeech/self-supervised-learning/multipatch-ssl/results/multipatch-ssl/20220301135129/save/CKPT+2022-03-01+17-26-55+00/patchies.ckpt'
output_norm: True
normalize_wav: True
output_hidden_states: False
hidden_state_layer: 8
freeze: !ref <freeze_patchies>

featurizer: !new:speechbrain.lobes.models.patchies.FbankFeaturizer
    n_mels: !ref <n_mels>
    hop_length: !ref <hop_length>

positional_embedding: !new:speechbrain.lobes.models.patchies.CAPE1d
    d_model: !ref <d_model>
    max_global_shift: !ref <max_global_shift>
    max_local_shift: !ref <max_local_shift>
    max_global_scaling: !ref <max_global_scaling>
    normalize: !ref <normalize_pos_emb>
    freq_scale: !ref <hop_length>
    batch_first: True

patcher: !new:speechbrain.lobes.models.patchies.PatchAndPos
    patch_sizes: !ref <patch_sizes>
    patch_strides: !ref <patch_strides>
    embedding_dim: !ref <d_model>
    feat_stride: !ref <hop_length>
    positional_embedding: !ref <positional_embedding>

target_patcher: !new:speechbrain.lobes.models.patchies.PatcherLayer
    patch_size: !ref <target_patch_size>
    patch_stride: !ref <target_patch_stride>
    embedding_dim: !ref <d_model>
    padding: True
    projector: False

feature_masker: !new:speechbrain.lobes.models.patchies.FeatureMasker
    mask_dim: !ref <mask_dim>
    mask_prob: !ref <mask_prob>
    mask_len: !ref <mask_length>
    len_sorting: !ref <batch_ordering>

contextualizer: !new:speechbrain.lobes.models.patchies.ContextExtractorBase

feature_projector: !new:speechbrain.lobes.models.patchies.FeatureProjector
    n_neurons: !ref <mask_dim>
    input_size: !ref <d_model>
    dropout: !ref <feat_projector_dropout>

decoder_pos_emb: !new:speechbrain.lobes.models.patchies.CAPE1d
    d_model: !ref <mask_dim>
    max_global_shift: !ref <max_global_shift>
    max_local_shift: !ref <max_local_shift>
    max_global_scaling: !ref <max_global_scaling>
    normalize: !ref <normalize_pos_emb>
    freq_scale: !ref <decoder_pos_emb_freq_scale>
    batch_first: True

decoder: !new:speechbrain.lobes.models.patchies.DecoderBase

upsampler: null

feat_to_patch_projector: !new:speechbrain.lobes.models.patchies.FeatureToPatchProjector
    patch_sizes: !ref <feat_patch_projector_patch_size>
    input_size: !ref <mask_dim>
    dropout: !ref <feat_patch_projector_dropout>

loss: !new:speechbrain.lobes.models.patchies.ReconstructionLoss

patchies: !new:speechbrain.lobes.models.patchies.Patchies
    featurizer: !ref <featurizer>
    patcher: !ref <patcher>
    target_patcher: !ref <target_patcher>
    feat_masker: !ref <feature_masker>
    contextualizer: !ref <contextualizer>
    feat_projector: !ref <feature_projector>
    decoder_pos_emb: !ref <decoder_pos_emb>
    decoder: !ref <decoder>
    upsampler: !ref <upsampler>
    feat_to_patch_projector: !ref <feat_to_patch_projector>
    loss: !ref <loss>

ctc_lin: !new:speechbrain.nnet.linear.Linear
   input_size: !ref <dnn_neurons>
   n_neurons: !ref <output_neurons>

log_softmax: !new:speechbrain.nnet.activations.Softmax
   apply_log: True

ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
   blank_index: !ref <blank_index>

modules:
   patchies: !ref <patchies>
   enc: !ref <enc>
   ctc_lin: !ref <ctc_lin>

model: !new:torch.nn.ModuleList
   - [!ref <enc>, !ref <ctc_lin>]

model_opt_class: !name:torch.optim.Adadelta
   lr: !ref <lr>
   rho: 0.95
   eps: 1.e-8

patchies_opt_class: !name:torch.optim.Adam
   lr: !ref <lr_patchies>

lr_annealing_model: !new:speechbrain.nnet.schedulers.NewBobScheduler
   initial_value: !ref <lr>
   improvement_threshold: 0.0025
   annealing_factor: 0.8
   patient: 0

lr_annealing_patchies: !new:speechbrain.nnet.schedulers.NewBobScheduler
   initial_value: !ref <lr_patchies>
   improvement_threshold: 0.0025
   annealing_factor: 0.9
   patient: 0


checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
   checkpoints_dir: !ref <save_folder>
   recoverables:
      patchies: !ref <patchies>
      model: !ref <model>
      scheduler_model: !ref <lr_annealing_model>
      scheduler_patchies: !ref <lr_annealing_patchies>
      counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
   save_file: !ref <train_log>

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
   split_tokens: True
